### ISSUE TITLE
STM32Cube FW_L4_V1.14.0 package breaks HAL time source init

### ISSUE THREAD

**Issue by Goldweavers** [Goldweavers/STM32L4_IMU#1]
Using a timer TIMx instead of SysTick as time base source the function HAL_InitTick() of the module stm32l4xx_hal_timebase_tim.c is overwriting the weak defined function of module stm32f1xx_hal.c.

Unfortunately the HAL_InitTick() function of stm32l4xx_hal_timebase_tim.c does not set the global variable uwTickPrio and therefore the assert check fails because uwTickPrio is initialized in stm32l4xx_hal.c with an invalid value.

**Comment by Goldweavers** [comment]
To fix this, we need to implement to following modifications in stm32l4xx_hal_timebase_tim.c:

Before modifications:
```
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
{
  RCC_ClkInitTypeDef clkconfig;
  uint32_t uwTimclock = 0;
  uint32_t uwPrescalerValue = 0;
  uint32_t pFLatency;

  /*Configure the TIM1 IRQ priority */
  HAL_NVIC_SetPriority (TIM1_UP_TIM16_IRQn, TickPriority, 0);

  /* Enable the TIM1 global Interrupt */
  HAL_NVIC_EnableIRQ (TIM1_UP_TIM16_IRQn);
```

After modifications:
```
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
{
  RCC_ClkInitTypeDef clkconfig;
  uint32_t uwTimclock = 0;
  uint32_t uwPrescalerValue = 0;
  uint32_t pFLatency;

  /*Configure the TIM1 IRQ priority */
  if (TickPriority < (1UL << __NVIC_PRIO_BITS))
	{
	  HAL_NVIC_SetPriority (TIM1_UP_TIM16_IRQn, TickPriority, 0);
	  uwTickPrio = TickPriority;
	}
  else
	return HAL_ERROR;

  /* Enable the TIM1 global Interrupt */
  HAL_NVIC_EnableIRQ (TIM1_UP_TIM16_IRQn);
```

**Comment by Goldweavers** [comment]
Resolved by commit [Fix HAL time source init](https://github.com/Goldweavers/STM32L4_IMU/commit/4ba490611421ee5a07beabef2dd08cf1720d3cc9)

**Comment by hisink** [comment]
> Resolved by commit [Fix HAL time source init](https://github.com/Goldweavers/STM32L4_IMU/commit/4ba490611421ee5a07beabef2dd08cf1720d3cc9)

It didn't really fix the issue.
In stm32wbxx_hal.c (or stm32f4xx, other people hit the same bug too.)
function HAL_SetTickFreq() has line
status = HAL_InitTick(uwTickPrio);
uwTickPrio is 1 << 4 => 16 in the same file. 
then it will get into HAL_ERROR
